version: '3'

services:
  app:
    build: .
    command: bash
    tty: true
    restart: always
    volumes:
    - ./:/code/
    # change the part before the colon to your vault
    - ~/Documents/notes/:/notes/
